name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache .m2 repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build
        run: ./mvnw -B package -Pcli
      # Do not run the parser, so we do not get failures because of breaking updates of the Spotify Web API reference
      #- name: Parse web API
      #  run: ./scripts/parse-web-api.sh
      - name: Generate Open API
        run: ./scripts/generate-open-api.sh
      - name: Generate TypeScript
        run: ./scripts/generate-ts.sh
      - name: Test
        run: ./mvnw -B clean verify
      - name: Check for generator results
        run: |
          git status --porcelain
          git diff --exit-code
